### ISSUE TITLE
Towards the second release of french language profile: differential file

### ISSUE THREAD

**Issue by caterina-lucano-orphanet** [obophenotype/hpo-translations#8]
Dear Nico @matentzn,

As Bruno @Bruno-Orpha-Paris has completed the first huge task of translating in French all the preferential terms (label) in our shared list, I would like to start working towards generating a differential file with the latest HPO released version, in order to be up to date with all the preferential terms for a second possible french language profile release. For this new version, we will also start working on synonyms, after completing the label differential.

Could you please instruct me on how to generate this file?

Thanks,

Caterina

**Comment by matentzn** [comment]
@caterina-lucano-orphanet according to our last meeting, we decide to not translate synonyms, but instead, curate them: https://github.com/obophenotype/hpo-translations/issues/5

Translations create a huge overhead here, especially when synonyms change - it is better if you simply say: For the concept X, we have, in french, the synonyms Y and Z. This is at least how we have remained during our last call!

**Comment by matentzn** [comment]
Alright, the first draft of the language profile is ready now! Thank you @Bruno-Orpha-Paris and the whole Orphanet team to work so hard on this.

I have already instructed @Bruno-Orpha-Paris how to work on the new spreadsheet. So whats missing is some operational decisions.

As you can see, not all classes in the current profile actually have their labels correct:

![image](https://user-images.githubusercontent.com/7070631/215727833-c9701025-c6eb-40bb-bb60-097ee34783b0.png)

(The majority do). The reason is that the label that was previously translated by Orphanet has changed since then in HPO. The question is here:

1. If the label changes, do we still want to include the old translation in the new profile? There are good arguments for this, including that the semantics never changes. I think we should, and we should, instead of removing the translation, simply classify it as "candidate translation" (instead of "OFFICIAL").
2. How should the hpo language profile exactly look like? My feeling is: It could be simple, i.e. all Uberon terms etc removed from it, to make it much smaller.. So in other words, just include the actual HPO axioms, not the imports. Playing with this now.

@caterina-lucano-orphanet @Bruno-Orpha-Paris let me know if you have opinions here!

**Comment by matentzn** [comment]
Here you can see an example of how synonyms are reflected:
![image](https://user-images.githubusercontent.com/7070631/215729889-17cc834f-e02b-40ec-83aa-dfa358d63cdb.png)

**Comment by matentzn** [comment]
The pipeline can be inspected here: https://github.com/obophenotype/human-phenotype-ontology/pull/7587 (you can also download the french language version of HPO from there if you want!)

**Comment by Bruno-Orpha-Paris** [comment]
> Alright, the first draft of the language profile is ready now! Thank you @Bruno-Orpha-Paris and the whole Orphanet team to work so hard on this.
> 
> I have already instructed @Bruno-Orpha-Paris how to work on the new spreadsheet. So whats missing is some operational decisions.
> 
> As you can see, not all classes in the current profile actually have their labels correct:
> 
> ![image](https://user-images.githubusercontent.com/7070631/215727833-c9701025-c6eb-40bb-bb60-097ee34783b0.png)
> 
> (The majority do). The reason is that the label that was previously translated by Orphanet has changed since then in HPO. The question is here:
> 
> 1. If the label changes, do we still want to include the old translation in the new profile? There are good arguments for this, including that the semantics never changes. I think we should, and we should, instead of removing the translation, simply classify it as "candidate translation" (instead of "OFFICIAL").
> 2. How should the hpo language profile exactly look like? My feeling is: It could be simple, i.e. all Uberon terms etc removed from it, to make it much smaller.. So in other words, just include the actual HPO axioms, not the imports. Playing with this now.
> 
> @caterina-lucano-orphanet @Bruno-Orpha-Paris let me know if you have opinions here!

Great ! Thank you for this work : )
1. yes, for those: i would also include the old translation in the new profile, with the annotation as "candidate".
2. yes, only the axiom seems enough.
